/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.ProjectPower;

@SuppressWarnings("all")
/** Methods that need to be implemented in the client if it is a candidate for controller election */
@org.apache.avro.specific.AvroGenerated
public interface ControllerCandidate {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ControllerCandidate\",\"namespace\":\"avro.ProjectPower\",\"doc\":\"Methods that need to be implemented in the client if it is a candidate for controller election\",\"types\":[],\"messages\":{\"electNewController\":{\"request\":[{\"name\":\"index\",\"type\":\"int\"},{\"name\":\"clientID\",\"type\":\"int\"}],\"response\":\"null\",\"one-way\":true}}}");
  void electNewController(int index, int clientID);

  @SuppressWarnings("all")
  /** Methods that need to be implemented in the client if it is a candidate for controller election */
  public interface Callback extends ControllerCandidate {
    public static final org.apache.avro.Protocol PROTOCOL = avro.ProjectPower.ControllerCandidate.PROTOCOL;
  }
}