/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ClientType { 
  Light, SmartFridge, User, TemperatureSensor  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ClientType\",\"namespace\":\"avro.proto\",\"symbols\":[\"Light\",\"SmartFridge\",\"User\",\"TemperatureSensor\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
