/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.ProjectPower;

@SuppressWarnings("all")
/** Methods for the TemperatureSensor class */
@org.apache.avro.specific.AvroGenerated
public interface communicationTempSensor {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"communicationTempSensor\",\"namespace\":\"avro.ProjectPower\",\"doc\":\"Methods for the TemperatureSensor class\",\"types\":[{\"type\":\"enum\",\"name\":\"ClientType\",\"symbols\":[\"Light\",\"SmartFridge\",\"User\",\"TemperatureSensor\"]}],\"messages\":{\"isAlive\":{\"request\":[],\"response\":\"boolean\"}}}");
  boolean isAlive() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** Methods for the TemperatureSensor class */
  public interface Callback extends communicationTempSensor {
    public static final org.apache.avro.Protocol PROTOCOL = avro.ProjectPower.communicationTempSensor.PROTOCOL;
    void isAlive(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}