/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.ProjectPower;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UserStatus { 
  present, absent  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserStatus\",\"namespace\":\"avro.ProjectPower\",\"symbols\":[\"present\",\"absent\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
