/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.DistUser;
import gui.PanelInterface;
/**
 *
 * @author federico
 */
public class FridgePanel extends javax.swing.JPanel implements PanelInterface{

    private DistUser f_user;
    
    /**
     * Creates new form FridgePanel
     * @param user
     *      The user on which the methods are being used
     */
    public FridgePanel(DistUser user) {
        initComponents();
        
        f_user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFridgeText = new javax.swing.JLabel();
        cbbSelectFridge = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(600, 400));

        lblFridgeText.setText("Choose a fridge:");

        cbbSelectFridge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFridgeText)
                .addGap(18, 18, 18)
                .addComponent(cbbSelectFridge, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFridgeText)
                    .addComponent(cbbSelectFridge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update() {
        // TODO add method here for updating when this panel is being focused
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbSelectFridge;
    private javax.swing.JLabel lblFridgeText;
    // End of variables declaration//GEN-END:variables
}
