/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.DistUser;
import client.exception.MultipleInteractionException;
import client.exception.AbsentException;
import client.exception.*;
import gui.PanelInterface;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import java.awt.Color;

/**
 *
 * @author federico
 */
public class TemperaturePanel extends javax.swing.JPanel implements PanelInterface {

    private DistUser f_user;
    /**
     * Creates new form TemperaturePanel
     * 
     * @param user
     *      The user on which the methods are used.
     */
    public TemperaturePanel(DistUser user) {
        initComponents();
        
        f_user = user;
        this.updateCurrentTemp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentTempText = new javax.swing.JLabel();
        btnGetCurrentTemp = new javax.swing.JButton();
        lblHistoryTempText = new javax.swing.JLabel();
        lblCurrentTemp = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        lblCurrentTempText.setText("Current temperature: ");

        btnGetCurrentTemp.setText("Update Temperatures");
        btnGetCurrentTemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetCurrentTempMouseClicked(evt);
            }
        });

        lblHistoryTempText.setText("History of temperatures:");

        lblCurrentTemp.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHistoryTempText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurrentTempText)
                        .addGap(63, 63, 63)
                        .addComponent(lblCurrentTemp)))
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetCurrentTemp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentTempText)
                    .addComponent(lblCurrentTemp))
                .addGap(18, 18, 18)
                .addComponent(lblHistoryTempText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(btnGetCurrentTemp)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetCurrentTempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetCurrentTempMouseClicked
        // TODO add your handling code here:
        this.updateCurrentTemp();
    }//GEN-LAST:event_btnGetCurrentTempMouseClicked

    private void updateCurrentTemp() {
        double currentTemp = 0;
        try {
            currentTemp = f_user.getCurrentTemperatureHouse();
        } catch (MultipleInteractionException e) {
            // TODO do something here
        } catch (AbsentException e) {
            // TODO do something here
        } catch (NoTemperatureMeasures e) {
            lblCurrentTemp.setText("No temperature measurements available yet.");
            return;
        } catch (TakeoverException e) {
            // TODO do something here
            return;
        }
        
        // lblCurrentTemp.setText(String.valueOf(currentTemp));
        lblCurrentTemp.setText(new DecimalFormat(".##").format(currentTemp));
    }
    
    @Override
    public void update() {
        // TODO add method here for updating when this panel is being focused
        this.updateCurrentTemp();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetCurrentTemp;
    private javax.swing.JLabel lblCurrentTemp;
    private javax.swing.JLabel lblCurrentTempText;
    private javax.swing.JLabel lblHistoryTempText;
    // End of variables declaration//GEN-END:variables
}
