/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.client.proto;

@SuppressWarnings("all")
/** Methods for the SmartFridge class */
@org.apache.avro.specific.AvroGenerated
public interface communicationFridge {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"communicationFridge\",\"namespace\":\"avro.client.proto\",\"doc\":\"Methods for the SmartFridge class\",\"types\":[],\"messages\":{\"addItemRemote\":{\"request\":[{\"name\":\"itemName\",\"type\":\"string\"}],\"response\":\"boolean\"},\"openFridgeRemote\":{\"request\":[],\"response\":\"boolean\"},\"closeFridgeRemote\":{\"request\":[],\"response\":\"boolean\"}}}");
  boolean addItemRemote(java.lang.CharSequence itemName) throws org.apache.avro.AvroRemoteException;
  boolean openFridgeRemote() throws org.apache.avro.AvroRemoteException;
  boolean closeFridgeRemote() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** Methods for the SmartFridge class */
  public interface Callback extends communicationFridge {
    public static final org.apache.avro.Protocol PROTOCOL = avro.client.proto.communicationFridge.PROTOCOL;
    void addItemRemote(java.lang.CharSequence itemName, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void openFridgeRemote(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void closeFridgeRemote(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}